site_name: Discordance
markdown_extensions:
  - codehilite
nav:
  - Github: 'https://github.com/NeverLucky123/Discordant_Transpiler/'
theme:
    name: material
    logo: 'favicon.png'
    favicon: 'favicon.png'
docs_dir: docs
site_dir: site
